### PR TITLE
2019 rewrite

### PR DESCRIPTION
**Pull request by lachenmayer**
As discussed in #2 

I changed all the bits referring to the fork & left the package.json version number at 1.0.0 to hopefully make it easier to publish this.

The full history can be seen here https://github.com/lachenmayer/buffer-json/tree/merge-upstream

Let me know if there are any other changes you'd like me to make.

### CODE REVIEW

**Comment by jprichardson** [comment]
1. Please restore CHANGELOG.md
2. If `.npmignore` is going to be removed, `package.json` needs a `files` field.

Rest looks good. I'll publish as 2.0.0.

**Comment by lachenmayer** [comment]
Have restored the changelog & .npmignore files, thanks!

**Comment by jprichardson** [comment]
Published as 2.0.0. Thank you.

**Comment by lachenmayer** [comment]
Amazing, thank you :)

**Pull request merged**
