### PR TITLE
fix error on some types of buffers

### PR DESCRIPTION
**Pull request by djulien**
Avoid trying to access undef var (buffer might be nested within a non-
buffer object)

### CODE REVIEW

**Comment by jprichardson** [comment]
Please do the following before I can accept this:
1. Add a test.
2. Don't modify package.json.
3. Run `npm test`.

Thanks :)

**Comment by djulien** [comment]
Thanks for the response.  Some questions:
1. For the test, do you want a test that used to fail and now passes with the change, or just a test that passes with old and new version?
2. Sorry, I thought a patch needed to bump the patch# of the version.  I will undo that one.
3. The package.json file appears to have a script for testing:
  "test": "standard && mocha"
However, "standard" is not defined anywhere that I can see - what is it?
For "mocha", is that just an "npm install"?  It's not listed in the dev dependencies so I wasn't sure if there are other steps needed for test as well.

**Comment by jprichardson** [comment]
1. Yep. A test that fails, but then passes with your change.
2. No worries, I like to do that along with the changelog.
3. Oops! Please run `npm i --save-dev mocha` and then `npm i --save-dev standard`.

Then you should be able to run `npm test` :)

**Comment by mistic** [comment]
@jprichardson  I think we can also close this PR as https://github.com/jprichardson/buffer-json/pull/3 replace it

**Pull request closed without merging**
